export const GameEngineActionTypes = {
  SET_NEW_LEVEL: 'SET_NEW_LEVEL',
  SET_RANDOM_ENGINE: 'SET_RANDOM_ENGINE',
  SET_PLAYER_GUESS: 'SET_PLAYER_GUESS',
  SET_CODE_SUM_PRODUCT: 'SET_CODE_SUM',
  SET_GUESS_SUM_PRODUCT: 'SET_GUESS_SUM',
};
