export const GameEngineActionTypes = {
  SET_NEW_LEVEL: 'SET_NEW_LEVEL',
  SET_GENERATED_CODE: 'SET_GENERATED_CODE',
  SET_CODEBASE: 'SET_CODEBASE',
  SET_PLAYER_GUESS: 'SET_PLAYER_GUESS',
  SET_PLAYER_CODES: 'SET_PLAYER_CODES',
};
